/*
Copyright 2023.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	"context"
	time "time"

	lbhcv1 "cloud.edge/lbhc-controller/apis/lbhc/v1"
	versioned "cloud.edge/lbhc-controller/client/clientset/versioned"
	internalinterfaces "cloud.edge/lbhc-controller/client/informers/externalversions/internalinterfaces"
	v1 "cloud.edge/lbhc-controller/client/listers/lbhc/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// LbhcInformer provides access to a shared informer and lister for
// Lbhcs.
type LbhcInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.LbhcLister
}

type lbhcInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewLbhcInformer constructs a new informer for Lbhc type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewLbhcInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredLbhcInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredLbhcInformer constructs a new informer for Lbhc type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredLbhcInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.LbhcV1().Lbhcs(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.LbhcV1().Lbhcs(namespace).Watch(context.TODO(), options)
			},
		},
		&lbhcv1.Lbhc{},
		resyncPeriod,
		indexers,
	)
}

func (f *lbhcInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredLbhcInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *lbhcInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&lbhcv1.Lbhc{}, f.defaultInformer)
}

func (f *lbhcInformer) Lister() v1.LbhcLister {
	return v1.NewLbhcLister(f.Informer().GetIndexer())
}
