# permissions for end users to view lbhcs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: lbhc-viewer-role
rules:
- apiGroups:
  - lbhc.cloud.edge
  resources:
  - lbhcs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - lbhc.cloud.edge
  resources:
  - lbhcs/status
  verbs:
  - get
