/*
Copyright 2023.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	lbhcv1 "cloud.edge/lbhc-controller/apis/lbhc/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeLbhcs implements LbhcInterface
type FakeLbhcs struct {
	Fake *FakeLbhcV1
	ns   string
}

var lbhcsResource = schema.GroupVersionResource{Group: "lbhc.cloud.edge", Version: "v1", Resource: "lbhcs"}

var lbhcsKind = schema.GroupVersionKind{Group: "lbhc.cloud.edge", Version: "v1", Kind: "Lbhc"}

// Get takes name of the lbhc, and returns the corresponding lbhc object, and an error if there is any.
func (c *FakeLbhcs) Get(ctx context.Context, name string, options v1.GetOptions) (result *lbhcv1.Lbhc, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(lbhcsResource, c.ns, name), &lbhcv1.Lbhc{})

	if obj == nil {
		return nil, err
	}
	return obj.(*lbhcv1.Lbhc), err
}

// List takes label and field selectors, and returns the list of Lbhcs that match those selectors.
func (c *FakeLbhcs) List(ctx context.Context, opts v1.ListOptions) (result *lbhcv1.LbhcList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(lbhcsResource, lbhcsKind, c.ns, opts), &lbhcv1.LbhcList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &lbhcv1.LbhcList{ListMeta: obj.(*lbhcv1.LbhcList).ListMeta}
	for _, item := range obj.(*lbhcv1.LbhcList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested lbhcs.
func (c *FakeLbhcs) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(lbhcsResource, c.ns, opts))

}

// Create takes the representation of a lbhc and creates it.  Returns the server's representation of the lbhc, and an error, if there is any.
func (c *FakeLbhcs) Create(ctx context.Context, lbhc *lbhcv1.Lbhc, opts v1.CreateOptions) (result *lbhcv1.Lbhc, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(lbhcsResource, c.ns, lbhc), &lbhcv1.Lbhc{})

	if obj == nil {
		return nil, err
	}
	return obj.(*lbhcv1.Lbhc), err
}

// Update takes the representation of a lbhc and updates it. Returns the server's representation of the lbhc, and an error, if there is any.
func (c *FakeLbhcs) Update(ctx context.Context, lbhc *lbhcv1.Lbhc, opts v1.UpdateOptions) (result *lbhcv1.Lbhc, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(lbhcsResource, c.ns, lbhc), &lbhcv1.Lbhc{})

	if obj == nil {
		return nil, err
	}
	return obj.(*lbhcv1.Lbhc), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeLbhcs) UpdateStatus(ctx context.Context, lbhc *lbhcv1.Lbhc, opts v1.UpdateOptions) (*lbhcv1.Lbhc, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(lbhcsResource, "status", c.ns, lbhc), &lbhcv1.Lbhc{})

	if obj == nil {
		return nil, err
	}
	return obj.(*lbhcv1.Lbhc), err
}

// Delete takes name of the lbhc and deletes it. Returns an error if one occurs.
func (c *FakeLbhcs) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(lbhcsResource, c.ns, name, opts), &lbhcv1.Lbhc{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeLbhcs) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(lbhcsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &lbhcv1.LbhcList{})
	return err
}

// Patch applies the patch and returns the patched lbhc.
func (c *FakeLbhcs) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *lbhcv1.Lbhc, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(lbhcsResource, c.ns, name, pt, data, subresources...), &lbhcv1.Lbhc{})

	if obj == nil {
		return nil, err
	}
	return obj.(*lbhcv1.Lbhc), err
}
